#!/usr/bin/php
<?php
define('SCRISSH_ROOT', getcwd());
require_once(SCRISSH_ROOT . '/lib/bootstrap.inc');

foreach($config['Servers'] as $key => $value) {
  echo "\n\033[1;36mEntering $key:\033[0;37m\n";
  $server = $config['Servers'][$key];
  $keys = $config['SSH']['keys'];
  $ssh = Shell::connect($server['host'], $server['port'], $server['user'], $keys['public-key'], $keys['private-key']);
  if($ssh) {
    foreach($server['commands'] as $key => $value) {
      echo($ssh->exec($server['commands'][$key]));
    }
  } else {
    echo("ERROR: Could not connect to server\n");
  }
}
?>
